#[derive(Debug, Clone)]
pub enum Action {
    FocusChange,
    ShowPlayerPicker(String, Option<String>),
    ShowPlaybackPicker(crate::providers::models::PlaybackSource),
    LaunchPlayer(crate::tui::state::PlayerKind, String, Option<String>),
    Tick,
    Key(crossterm::event::KeyEvent),
    Quit,
    GoBack,
    SelectLanguage(usize),
    Resize(u16, u16),
    ToggleHelp,
    ToggleTvMode,
    SwitchProvider(crate::providers::models::ProviderKind),
    OpenProviderPicker,
    SetSearchScope(crate::providers::models::SearchScope),
    ShowTvWizard,
    TvChannelsLoaded(Vec<crate::providers::iptv_org::m3u::Channel>),
    Search {
        query: String,
        force_refresh: bool,
    },
    SelectSuggestion {
        query: String,
    },
    SearchSuccess {
        context: crate::providers::models::RequestContext,
        query: String,
        payload: serde_json::Value,
    },
    SearchFailure(crate::providers::models::RequestContext, String),
    FetchHomepage {
        tab_id: String,
        page: usize,
    },
    HomepageSuccess {
        tab_id: String,
        page: usize,
        payload: serde_json::Value,
    },
    HomepageFailure(String),
    Suggest(String),
    SuggestSuccess(String, serde_json::Value),
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    Submit,
    TabPane,
    BackTabPane,
    FetchPreview(String),
    PreviewSuccess(String, serde_json::Value),
    PreviewFailure(String),
    PlayStream(bool),
    ShowSubtitlePopup(String, serde_json::Value, bool),
    ShowDownloadSubtitlePopup(serde_json::Value),
    LaunchMpv(String, Option<String>),
    PlayersDetected(Vec<crate::tui::state::PlayerKind>),
    DownloadStream(Option<String>),
    StartDownload(Option<String>, Option<String>),
    UpdateDownload(Option<f64>, Option<String>),
    DownloadCompleted(String),
    DownloadFailed(String),
    DownloadPaused(String),
    ClearDownload,
    CancelDownload,
    PromptDownloadEpisode,
    ConfirmDownloadEpisode,
    PromptDownloadSeason,
    ConfirmDownloadSeason,
    ProcessDownloadQueue,
    FetchDetails(String, bool),
    DetailsSuccess(
        crate::providers::models::RequestContext,
        String,
        serde_json::Value,
    ),
    DetailsFailure(crate::providers::models::RequestContext, String),
    InitStreamPool(String),
    StreamPoolInitialized(String, Vec<u32>),
    FetchEpisodeStreams {
        subject_id: String,
        season: usize,
        episode: usize,
        force_refresh: bool,
    },
    EpisodeStreamsReady(
        crate::providers::models::RequestContext,
        u64,
        String,
        usize,
        usize,
        serde_json::Value,
    ),
    EpisodeStreamsFailed(
        crate::providers::models::RequestContext,
        u64,
        String,
        usize,
        usize,
        String,
    ),
    PosterSuccess(String, std::sync::Arc<image::DynamicImage>),
    SearchPosterLoaded(String, Option<std::sync::Arc<image::DynamicImage>>),
    UpdateAvailable(String),
    CheckForUpdates,
    SetStatus(String),
    Refresh,
    ClearCache,
    LaunchPlayback(
        crate::tui::state::PlayerKind,
        crate::providers::models::PlaybackSource,
    ),
    OpenLibrary,
    RefreshLibrary,
    PlayLibraryItem {
        open_with: bool,
    },
    OpenContinueWatching,
    ResumeContinueItem {
        open_with: bool,
    },
    RemoveContinueItem,
    /// Player quit — persist exact resume position from watch-later.
    WatchPositionSaved {
        key: String,
        position_secs: f64,
        duration_secs: Option<f64>,
    },
}
